// Treści podstron branżowych (SEO landing pages)
export const industries = [
  {
    slug: 'gastronomia',
    name: 'Gastronomia',
    icon: 'utensils',
    tag: 'operacje lokalu',
    color: '#f6dacc',
    seoTitle: 'System dla gastronomii — zapotrzebowanie, grafik, koszty | Modulio',
    seoDescription: 'Oprogramowanie dla restauracji, kawiarni i cateringu: zapotrzebowanie i zakupy, koszty produktów, grafik zmian, czas pracy i rentowność lokalu w jednym systemie.',
    title: 'Zaplecze, które wie, czego brakuje — zanim zabraknie.',
    lead: 'Kontroluj zapotrzebowanie, ceny produktów, grafik, czas pracy i koszty operacyjne bez kolejnych arkuszy.',
    features: ['Zapotrzebowanie', 'Koszty produktów', 'Grafik', 'Czas pracy'],
    board: [['shopping-basket', 'Zakupy i dostawy', 'Listy zapotrzebowania i ceny'], ['clock-3', 'Czas zespołu', 'Zmiany i ewidencja pracy'], ['chart-pie', 'Rentowność', 'Koszt operacyjny i wynik']],
    pains: ['Zamówienia do dostawców w wiadomościach i na kartkach', 'Ceny produktów rosną, a karta menu stoi w miejscu', 'Grafik w arkuszu, zmiany ustalane na czacie', 'Brak wiedzy, ile naprawdę zarabia lokal w danym tygodniu'],
    modules: [
      ['clipboard-list', 'Zapotrzebowanie i zakupy', 'Zespół zgłasza braki, manager zatwierdza listę, a dostawy trafiają do historii z cenami.'],
      ['calculator', 'Koszt produktów i receptur', 'Aktualne ceny zakupu przeliczają koszt porcji i marżę pozycji w menu.'],
      ['calendar-days', 'Grafik zmian', 'Plan tygodnia, dostępność pracowników, zamiany zmian i powiadomienia.'],
      ['clock-3', 'Ewidencja czasu pracy', 'Wejścia i wyjścia, nadgodziny i zestawienia do rozliczeń.'],
      ['store', 'Wiele lokali', 'Wspólny standard i osobne wyniki dla każdej lokalizacji.'],
      ['chart-pie', 'Wynik operacyjny', 'Przychód, food cost, koszty pracy i wynik tygodnia na jednym ekranie.'],
    ],
    faq: [
      ['Czy system obsłuży kilka lokali?', 'Tak. Każda lokalizacja ma własny grafik, zapotrzebowanie i wyniki, a właściciel widzi zestawienie całej sieci.'],
      ['Czy pracownicy mogą korzystać z telefonu?', 'Tak. Widok pracownika jest projektowany jako responsywna aplikacja webowa — grafik i zgłoszenia działają na telefonie.'],
      ['Czy Modulio zastępuje system POS?', 'Nie musi. Najczęściej uzupełniamy istniejący POS o zaplecze operacyjne, a tam, gdzie to możliwe, integrujemy dane sprzedażowe.'],
    ],
  },
  {
    slug: 'uslugi-serwis',
    name: 'Usługi i serwis',
    icon: 'wrench',
    tag: 'zlecenia terenowe',
    color: '#d9e6dd',
    seoTitle: 'System do zleceń serwisowych i firm usługowych | Modulio',
    seoDescription: 'Program do obsługi zleceń dla firm usługowych i serwisowych: karta zlecenia, wyceny, kalendarz ekip, koszty realizacji i rentowność każdego zlecenia.',
    title: 'Od telefonu klienta do zamkniętego zlecenia.',
    lead: 'Adres, termin, wycena, pracownik, koszty i status realizacji są częścią jednego procesu, a nie pięciu osobnych narzędzi.',
    features: ['Zlecenia', 'Kalendarz', 'Klienci', 'Pracownicy'],
    board: [['clipboard-list', 'Karta zlecenia', 'Adres, termin, kwota, status'], ['calendar-days', 'Plan realizacji', 'Przydział pracowników i terminy'], ['badge-dollar-sign', 'Wynik zlecenia', 'Przychód kontra koszt realizacji']],
    pains: ['Zlecenia zapisane w notesie, SMS-ach i mailach', 'Ekipa nie wie, gdzie jedzie jutro', 'Nikt nie wie, które zlecenia są naprawdę opłacalne', 'Historia klienta ginie razem z odejściem pracownika'],
    modules: [
      ['clipboard-list', 'Karta zlecenia', 'Zakres, adres, termin, kwota, zdjęcia i status w jednym rekordzie.'],
      ['file-text', 'Wyceny', 'Szablony wycen, pozycje, rabaty i akceptacja przez klienta.'],
      ['calendar-days', 'Kalendarz ekip', 'Przydział pracowników, obciążenie i plan dnia.'],
      ['contact-round', 'Klienci / CRM', 'Historia zleceń, notatki, urządzenia i dane kontaktowe.'],
      ['receipt-text', 'Koszty realizacji', 'Materiały, czas pracy i dojazdy przypięte do zlecenia.'],
      ['badge-dollar-sign', 'Rentowność', 'Wynik każdego zlecenia, typu usługi i pracownika.'],
    ],
    faq: [
      ['Czy pracownik terenowy zamknie zlecenie z telefonu?', 'Tak — może zmienić status, dodać zdjęcia, notatkę i czas pracy bezpośrednio z telefonu.'],
      ['Czy klient może zgłosić zlecenie przez formularz?', 'Tak. Formularz na stronie może tworzyć kartę klienta i nowe zlecenie automatycznie.'],
      ['Czy można wystawiać wyceny w PDF?', 'Tak, wyceny generujemy według Twojego szablonu i wysyłamy do klienta z systemu.'],
    ],
  },
  {
    slug: 'transport',
    name: 'Transport',
    icon: 'truck',
    tag: 'mobilne zespoły',
    color: '#dce5f1',
    seoTitle: 'System dla transportu i przeprowadzek — wyceny, trasy, koszty | Modulio',
    seoDescription: 'Oprogramowanie dla firm transportowych i przeprowadzkowych: wyceny, planowanie tras i ekip, koszty paliwa i pojazdów oraz rentowność każdej realizacji.',
    title: 'Wycena, trasa, ekipa i koszt — wszystko spięte w jedno zlecenie.',
    lead: 'Dla transportu, przeprowadzek i usług mobilnych. System liczy koszty, planuje pracę i pokazuje rentowność każdej realizacji.',
    features: ['Wyceny', 'Trasy', 'Koszty paliwa', 'Pojazdy'],
    board: [['route', 'Trasy i adresy', 'Plan dnia oraz miejsca realizacji'], ['fuel', 'Koszty pojazdu', 'Paliwo i koszty bezpośrednie'], ['users-round', 'Ekipa', 'Pracownicy przypisani do zlecenia']],
    pains: ['Wyceny liczone „na oko” i w arkuszu', 'Koszty paliwa i opłat rozliczane po miesiącu', 'Pojazdy i ekipy planowane przez telefon', 'Brak wiedzy, które trasy przynoszą stratę'],
    modules: [
      ['calculator', 'Kalkulator wyceny', 'Stawki, kilometry, piętra, ekipa i dodatki liczone automatycznie.'],
      ['route', 'Plan tras', 'Adresy, kolejność realizacji i plan dnia dla każdej ekipy.'],
      ['truck', 'Flota', 'Pojazdy, przeglądy, ubezpieczenia i przypomnienia o terminach.'],
      ['fuel', 'Koszty pojazdów', 'Paliwo, opłaty drogowe i serwis przypięte do realizacji.'],
      ['users-round', 'Ekipy', 'Skład ekip, dostępność i czas pracy.'],
      ['chart-spline', 'Rentowność tras', 'Przychód kontra koszt na zleceniu, trasie i pojeździe.'],
    ],
    faq: [
      ['Czy system policzy wycenę przeprowadzki?', 'Tak, budujemy kalkulator na Twoich stawkach: kilometry, objętość, piętra, liczba osób i usługi dodatkowe.'],
      ['Czy da się śledzić koszty każdego pojazdu?', 'Tak — paliwo, serwis i opłaty są przypisane do pojazdu i zlecenia, więc widzisz koszt na kilometr.'],
      ['Czy można zintegrować GPS?', 'W projektach rozszerzonych integrujemy dane z dostawców telematyki przez API.'],
    ],
  },
  {
    slug: 'beauty-wellness',
    name: 'Beauty & wellness',
    icon: 'sparkles',
    tag: 'wizyty i klienci',
    color: '#ebdfed',
    seoTitle: 'System dla salonu beauty i wellness — wizyty, klienci, grafik | Modulio',
    seoDescription: 'Oprogramowanie dla salonów beauty, SPA i gabinetów: kalendarz wizyt, historia klienta, grafik specjalistów, usługi i raporty wykonanej pracy.',
    title: 'Mniej chaosu w grafiku. Więcej uwagi dla klienta.',
    lead: 'Wizyty, historia klienta, usługi, grafik specjalistów i raport wykonanej pracy mogą działać w jednym panelu.',
    features: ['Wizyty', 'Historia klienta', 'Grafik', 'Usługi'],
    board: [['calendar-heart', 'Wizyty', 'Terminy i potwierdzenia'], ['contact-round', 'Klienci', 'Historia usług i notatki'], ['scissors', 'Usługi', 'Cennik i wykonana praca']],
    pains: ['Kalendarz w zeszycie lub w kilku aplikacjach', 'Klienci zapominają o wizytach', 'Historia zabiegów rozproszona między specjalistami', 'Rozliczenie prowizji zajmuje godziny'],
    modules: [
      ['calendar-heart', 'Kalendarz wizyt', 'Wizyty, stanowiska, specjaliści i czas trwania usług.'],
      ['bell-ring', 'Przypomnienia', 'Automatyczne SMS / e-mail z potwierdzeniem wizyty.'],
      ['contact-round', 'Karta klienta', 'Historia zabiegów, preferencje, zgody i notatki.'],
      ['scissors', 'Usługi i cennik', 'Katalog usług, warianty i czas realizacji.'],
      ['users-round', 'Grafik specjalistów', 'Dostępność, urlopy i obciążenie zespołu.'],
      ['chart-column', 'Raporty i prowizje', 'Obroty, wykonane usługi i rozliczenia specjalistów.'],
    ],
    faq: [
      ['Czy klienci mogą umawiać się sami online?', 'Tak, możemy dodać moduł rezerwacji online połączony z grafikiem specjalistów.'],
      ['Czy system przechowuje zgody klientów?', 'Tak — karta klienta może zawierać zgody i notatki z kontrolą, kto ma do nich dostęp.'],
      ['Czy da się liczyć prowizje?', 'Tak, na podstawie wykonanych usług i reguł prowizyjnych ustalonych dla zespołu.'],
    ],
  },
  {
    slug: 'handel',
    name: 'Handel',
    icon: 'store',
    tag: 'towar i stany',
    color: '#ece5cf',
    seoTitle: 'System magazynowy dla handlu — stany, dostawy, raporty | Modulio',
    seoDescription: 'Oprogramowanie dla sklepów i hurtowni: katalog produktów, stany magazynowe, dostawy, zapotrzebowanie i raporty sprzedaży — także dla wielu lokalizacji.',
    title: 'Wiesz, co masz, czego brakuje i co naprawdę się sprzedaje.',
    lead: 'Katalog produktów, dostawy, stany, zapotrzebowanie i raporty w jednym miejscu — także dla wielu lokalizacji.',
    features: ['Produkty', 'Stany', 'Dostawy', 'Raporty'],
    board: [['package-search', 'Stany magazynowe', 'Aktualna liczba produktów'], ['truck', 'Dostawy', 'Przyjęcia i historia zmian'], ['chart-column', 'Sprzedaż', 'Najważniejsze dane produktowe']],
    pains: ['Stany w arkuszu nie zgadzają się z półką', 'Braki wychodzą dopiero przy kliencie', 'Przesunięcia między sklepami „na słowo”', 'Brak wiedzy, które produkty zamrażają gotówkę'],
    modules: [
      ['package-search', 'Katalog i stany', 'Produkty, warianty, kody i aktualne stany w każdej lokalizacji.'],
      ['truck', 'Dostawy i przyjęcia', 'Zamówienia do dostawców, przyjęcia i historia cen zakupu.'],
      ['arrow-left-right', 'Przesunięcia MM', 'Ruchy towaru między magazynami i sklepami.'],
      ['bell-ring', 'Alerty braków', 'Minimalne stany i automatyczne listy zapotrzebowania.'],
      ['scan-barcode', 'Inwentaryzacja', 'Spis z natury z telefonu i raport różnic.'],
      ['chart-column', 'Raporty sprzedaży', 'Rotacja, marża i produkty zamrażające gotówkę.'],
    ],
    faq: [
      ['Czy system współpracuje ze sklepem internetowym?', 'Tak, w ramach integracji synchronizujemy produkty i stany z popularnymi platformami e-commerce przez API.'],
      ['Czy można skanować kody kreskowe telefonem?', 'Tak — inwentaryzacja i przyjęcia mogą działać z aparatu telefonu lub czytnika.'],
      ['Czy obsłużycie kilka magazynów?', 'Tak, każda lokalizacja ma własne stany, a przesunięcia są rejestrowane w historii.'],
    ],
  },
];
